baseURL: 'http://LucasFA.github.io/'
languageCode: 'en-us'
title: 'LucasFA'
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: About
                  url: about
                  weight: 1
                # - name: Blog
                  # url: blog
                  # weight: 1
                # - name: Resume
                  # url: resume
                  # weight: 1 
                # - name: Search
                #   url: search/
                #   weight: 10
               # - name: Archive
                #   url: archives
                #   weight: 5
                # - name: Tags
                #   url: tags/
                #   weight: 10
outputs:
    home:
        - HTML
        - RSS
        # - JSON

params:
    math: true
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "This is my blog site."
    author: 
    # author: ["Me", "You"] # multiple authors
    homeInfoParams:
      Title: "Hi There :wave:"
      Content: "Welcome to my blog"
    socialIcons:


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShareButtons: [ "reddit", "linkedin", "whatsapp", "telegram"]
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    # comments: false
    # images: ["papermod-cover.png"]

    # profileMode:
    #     enabled: false
    #     title: PaperMod
    #     imageUrl: "#"
    #     imageTitle: my image
    #     # imageWidth: 120
    #     # imageHeight: 120
    #     buttons:
    #         - name: Archives
    #           url: archives
    #         - name: Tags
    #           url: tags

    # homeInfoParams:
    #     Title: "PaperMod"
        # Content: >
        #     Welcome to demo of hugo's theme PaperMod.

        #     - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.

        #     - Do give a 🌟 on Github !

        #     - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

    socialIcons:
        - name: github
          url: "https://github.com/LucasFA"
        - name: linkedin
          url: "https://linkedin.com/in/lucas-fa"
        - name: Rss
          url: "index.xml"

    editPost:
        URL: "https://github.com/LucasFA/LucasFA.github.io/edit/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - '\['
            - '\]'
          - - $$
            - $$
          inline:
          - - '\('
            - '\)'
        enable: true

privacy:
    vimeo:
        disabled: false
        simple: true

    x:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    x:
        disableInlineCSS: true
